server:
  port: 9000
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - SaveSession
        - TokenRelay
      routes:
        - id: vocabulary-service
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1/vocab/**
        - id: quiz-service
          uri: http://localhost:9002
          predicates:
            - Path=/api/v1/quizzes/**
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: api-keycloak-secret
            scope: openid,roles
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/Education

logging:
  level:
    org.springframework.security: DEBUG