server:
  port: 9000
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s



spring:
  application:
    name: edge-service
  # routes:
  #  - id: vocab-route
  #    uri: http://localhost:9001
  #    predicates:
  #      - Path=/vocabulary/**
  #  Configuring the integration between Spring Security and Keycloak
  security:
    oauth2:
      client:
        registration:
          keycloak:   # Each Client registration in Spring Security must have an identifier (registrationId)
            client-id: edge-service
            client-secret: keycloak-secret
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/Education
