INSERT INTO vocabularies (topic, word, level, type, pronunciation, definition, example)
VALUES
    ('LEISURE AND RECREATION',
    'football',
    'A1',
    'noun',
    '/ˈfʊtbɔːl/',
    'Đá bóng',
    'The kids were outside playing football.'),

    ('LEISURE AND RECREATION',
    'gym',
    'A1',
    'noun',
    '/dʒɪm/',
    'Phòng tập thể dục',
    'The school has recently built a new gym.'),

    ('LEISURE AND RECREATION',
    'hiking',
    'A1',
    'noun',
    '/ˈhaɪkɪŋ/',
    'Đi bộ đường dài',
    'He loves hiking.'),

    ('LEISURE AND RECREATION',
    'reading',
    'A1',
    'noun',
    '/ˈriːdɪŋ/',
    'Đọc sách',
    'My hobbies include reading and painting.'),

    ('LEISURE AND RECREATION',
    'cooking',
    'A1',
    'noun',
    '/ˈkʊkɪŋ/',
    'Nấu ăn',
    'My husband does all the cooking.');